"use client"
import './globals.css'
import Head from 'next/head'
import 'bootstrap/dist/css/bootstrap.min.css';
import React, { useEffect } from 'react';
import AOS from 'aos';
import 'aos/dist/aos.css';
import { Inter } from 'next/font/google'


import 'slick-carousel/slick/slick.css';
import 'slick-carousel/slick/slick-theme.css';

import Footer from './components/Footer';
import Header from './components/Header';


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  useEffect(() => {
    AOS.init();
  }, []);

  return (
    <html lang="en">
      <Head>
       <title>Helllow</title>

      </Head>


      <body className={inter.className}>


        <Header/>
        {children}
        <Footer/>



        </body>
    </html>
  )
}
